version: "3.4"

services:
  jenkins-agent-maven:
    image: maxfouquet/jnlp-maven-slave
    container_name: jenkins-agent-maven
    networks:
      - ci-net
    environment:
      JENKINS_URL: ${JENKINS_PROTOCOL}://${JENKINS_HOST}:${JENKINS_PORT}
      JENKINS_AUTH: ${JENKINS_USERNAME}:${JENKINS_PASSWORD}
      JENKINS_SLAVE_NAME: maven
      JENKINS_SLAVE_NUM_EXECUTORS: 2
    restart: on-failure

  jenkins-agent-node:
    image: maxfouquet/jnlp-node-slave
    container_name: jenkins-agent-node
    networks:
      - ci-net
    environment:
      JENKINS_URL: ${JENKINS_PROTOCOL}://${JENKINS_HOST}:${JENKINS_PORT}
      JENKINS_AUTH: ${JENKINS_USERNAME}:${JENKINS_PASSWORD}
      JENKINS_SLAVE_NAME: node
      JENKINS_SLAVE_NUM_EXECUTORS: 2
    restart: on-failure

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - ci-net
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    networks:
      - ci-net
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres
    container_name: postgres
    networks:
      - ci-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  ci-net:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data: